prop:
  upload-folder: files/
spring:
  http:
    multipart:
      max-file-size: 3MB
  mail:
    default-encoding: UTF-8
    host: smtp.263.net
    port: 25
    protocol: smtp
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.240.254:3307/asa_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: ASA_root
  quartz:
      wait-for-jobs-to-complete-on-shutdown: true
      job-store-type: memory
  messages:
      basename: i18n/messages
mybatis:
   mapperLocations: classpath:/mapper/*.xml
